name: dbps_pred
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - streamlit=1.31.1
  - pandas=2.2.0
  - numpy=1.26.3
  - scikit-learn=1.4.0
  - pillow=10.2.0
  - matplotlib=3.8.2
  - seaborn=0.13.2 